name: Deploy Flutter Web to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar codigo
        uses: actions/checkout@v6

      - name: Instalar Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Compilar Flutter Web
        run: flutter build web --release --base-href "/gutipal-style/"

      - name: Configurar GitHub Pages
        uses: actions/configure-pages@v5

      - name: Subir archivos web
        uses: actions/upload-pages-artifact@v4
        with:
          path: build/web

  deploy:
    needs: build
    runs-on: ubuntu-latest

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Publicar en GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4